### ISSUE TITLE
Import issiue

### ISSUE THREAD

**Issue by armandomendosa** [Azure/azure-iot-sdk-python-preview#103]
Hi

I have issiue with library import. OS WIN10 checked with 2 machines.

1. First clean python 3.7.2 instalation, package installed using pip.
2. Some other python versions were previously installed, then uninstalled. Now clean python 3.7.2 is installed (first 3.7.X instalation).

In both cases I got same issiue with running sample app:

python send_telemetry.py
Traceback (most recent call last):
  File "send_telemetry.py", line 12, in <module>
    from azure.iot.device.iothub import Message
ModuleNotFoundError: No module named 'azure'

pip freeze output

azure-iot-device==2.0.0rc5
certifi==2019.3.9
chardet==3.0.4
idna==2.8
janus==0.4.0
paho-mqtt==1.4.0
requests==2.22.0
requests-unixsocket==0.1.5
six==1.12.0
transitions==0.6.9
urllib3==1.24.3

Thanks in advance 
Maciej

**Comment by cartertinney** [comment]
Maciej, we will begin looking into this. Was your Python 3.7.2 installed as plain Python or via Anaconda?

**Comment by armandomendosa** [comment]
Hi

I've used plain Python:

https://www.python.org/downloads/release/python-372/

Windows x86-64 executable installer | Windows | for AMD64/EM64T/x64

**Comment by cartertinney** [comment]
@armandomendosa I've identified the problem as being a bug in our latest release. I'm going to get to work on finding and fixing the issue, but in the meantime, you can use our last official release that does work

`pip install azure-iot-device=2.0.0rc4 --force-reinstall`

**Comment by cartertinney** [comment]
Issue has been fixed in release 2.0.0-preview6 (2.0.0-rc6). Please install the latest version with pip, and the issue should be resolved

`pip install azure-iot-device --upgrade`

**Comment by armandomendosa** [comment]
Works fine. Thanks for fix :)
