### ISSUE TITLE
Direct method async listner execut twice

### ISSUE THREAD

**Issue by armandomendosa** [Azure/azure-iot-sdk-python-preview#108]
Hi

I was testing API by playing arrount with:
azure-iot-sdk-python-preview/azure-iot-device/samples/advanced-hub-scenarios/receive_direct_method.py  

I have notice that when I push direct method from azure IOT hub or my web app function defines as callback for async listner execute it's own twice (i see it by dupilcated print messages). I am using also API for C# and there in that case callback execute only once. 

Is that expected behaviour?

**Comment by cartertinney** [comment]
Thank you for raising this issue. We have successfully replicated the problem and are looking into solutions now.

**Comment by cartertinney** [comment]
The solution has been identified and we are currently implementing a fix.

**Comment by cartertinney** [comment]
This has been fixed in #115 . It will be included in the next pip release at the end of the month.
