### ISSUE TITLE
Cannot register device using x509

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python-preview#139]
I have created certificates as per [CA Certificate Overview](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) and am trying to use them for device provisioning.
I've used that certificate to create an enrollment group in my Device Provisioning Service in Azure portal, and linked that group to an IoT Hub.
Now trying to run register_x509.py program with these values:
provisioning_host="global.azure-devices-provisioning.net"
registration_id = mydeviceID
X509_CERT_FILE == path of root CA certificate pem file
X509_KEY_FILE ==  path of root CA private key pem file

Below is the program's output:
`INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage(SetX509SecurityClientOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:PipelineRootStage(SetX509SecurityClientOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSecurityClientStage(SetX509SecurityClientOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetSecurityClientArgsOperation):run_ops_serial: starting first op.
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetSecurityClientArgsOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(SetSecurityClientArgsOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:EnsureConnectionStage(SetSecurityClientArgsOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverterStage(SetSecurityClientArgsOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(SetSecurityClientArgsOperation): continuing with SetMQTTConnectionArgsOperation op
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(SetMQTTConnectionArgsOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:MQTTClientStage(SetMQTTConnectionArgsOperation): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTClientStage(SetMQTTConnectionArgsOperation): got connection args
INFO:azure.iot.device.common.mqtt_client_operator:creating mqtt client
INFO:azure.iot.device.common.mqtt_client_operator:Created MQTT protocol client, assigned callbacks
INFO:azure.iot.device.common.pipeline.operation_flow:MQTTClientStage(SetMQTTConnectionArgsOperation): completing without error
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(SetSecurityClientArgsOperation): completing with result from SetMQTTConnectionArgsOperation
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(SetSecurityClientArgsOperation): completing without error
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetSecurityClientArgsOperation):run_ops_serial: completed. 1 items left
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetSecurityClientArgsOperation):run_ops_serial: op succeeded. running next op in list.
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetClientAuthenticationCertificateOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(SetClientAuthenticationCertificateOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:EnsureConnectionStage(SetClientAuthenticationCertificateOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverterStage(SetClientAuthenticationCertificateOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(SetClientAuthenticationCertificateOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:MQTTClientStage(SetClientAuthenticationCertificateOperation): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTClientStage(SetClientAuthenticationCertificateOperation): got certificate
INFO:azure.iot.device.common.pipeline.operation_flow:MQTTClientStage(SetClientAuthenticationCertificateOperation): completing without error
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetClientAuthenticationCertificateOperation):run_ops_serial: completed. 0 items left
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetClientAuthenticationCertificateOperation):run_ops_serial: last op succeeded.
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(SetClientAuthenticationCertificateOperation):run_ops_serial: no finally_op.  calling back.
INFO:azure.iot.device.provisioning.aio.async_provisioning_device_client:Registering with Provisioning Service...
INFO:azure.iot.device.provisioning.internal.polling_machine:register called from polling machine
INFO:azure.iot.device.provisioning.internal.polling_machine:Initializing the registration process.
INFO:azure.iot.device.provisioning.pipeline.provisioning_pipeline:enable_responses called
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage(EnableFeatureOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:PipelineRootStage(EnableFeatureOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSecurityClientStage(EnableFeatureOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:UseSecurityClientStage(EnableFeatureOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): enabling block
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): queueing until connection complete
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): calling down with Connect operation
INFO:azure.iot.device.common.pipeline.operation_flow:EnsureConnectionStage(ConnectOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverterStage(ConnectOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(ConnectOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:MQTTClientStage(ConnectOperation): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTClientStage(ConnectOperation): conneting
INFO:azure.iot.device.common.mqtt_client_operator:connecting to mqtt broker
INFO:azure.iot.device.common.mqtt_client_operator:creating a SSL context
INFO:azure.iot.device.common.mqtt_client_operator:configuring SSL context with client-side certificate and key
INFO:transitions.core:Exited state disconnected
INFO:transitions.core:Entered state initializing
INFO:azure.iot.device.provisioning.internal.polling_machine:Transition complete.  Trigger=_trig_register, Src=disconnected, Dest=initializing, result=True, errorNone
INFO:azure.iot.device.common.mqtt_client_operator:connected with result code: 5
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTClientStage(ConnectOperation): on_connected.  completing op.
INFO:azure.iot.device.common.pipeline.operation_flow:MQTTClientStage(ConnectOperation): completing without error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): connection is complete
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): disabling block and releasing queued ops.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): processing 1 items in queue
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): releasing EnableFeatureOperation op.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnectionStage(EnableFeatureOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:EnsureConnectionStage(EnableFeatureOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverterStage(EnableFeatureOperation): running
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(EnableFeatureOperation): continuing with MQTTSubscribeOperation op
INFO:azure.iot.device.common.pipeline.operation_flow:ProvisioningMQTTConverterStage(MQTTSubscribeOperation): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:MQTTClientStage(MQTTSubscribeOperation): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTClientStage(MQTTSubscribeOperation): subscribing to $dps/registrations/res/#
INFO:azure.iot.device.common.mqtt_client_operator:subscribing to $dps/registrations/res/# with qos 1
INFO:azure.iot.device.common.mqtt_client_operator:Waiting for response on MID: 1
INFO:azure.iot.device.common.mqtt_client_operator:disconnected with result code: 5
INFO:azure.iot.device.common.mqtt_client_operator:connected with result code: 5
INFO:azure.iot.device.common.mqtt_client_operator:disconnected with result code: 5
INFO:azure.iot.device.common.mqtt_client_operator:connected with result code: 5
`
This is where it goes on kinda forever, unless I interrupt it. No device gets attached to my IoT Hub.
Which steps have I done incorrectly?
I also tried to use these certificates with individual enrollment, and to use the provisioning service endpoint URL instead of global service endpoint. None of these changes succeeded.

**Comment by olivakar** [comment]
What is the common name of the leaf certificate that you have created ?

**Comment by bukarev** [comment]
@olivakar same as registration_id:
`Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3 (0x3)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = my-iot-intermediate
        Validity
            Not Before: Jul 16 00:53:56 2019 GMT
            Not After : Jul 13 00:53:56 2029 GMT
        **Subject: CN = device1**
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)`

My code:
`provisioning_host = "global.azure-devices-provisioning.net"
id_scope = "0ne000(skipped)"
**registration_id = "device1"**
`

**Comment by bukarev** [comment]
@olivakar exactly what certificate I should be passing along? I noticed in the scripts directory there's a .py code for generating certificates. Should I use that script to generate certificates rather than openSSL-based procedure I referred to? If so, what's the sequence of steps for certificate verification?

**Comment by olivakar** [comment]
Could you check the following things :

1. Have you done proof of possession for the root certificate that you generated ?
2. Which certificate along the chain did you use to create the enrollment group ?
3. The sample must send the entire chain except the one verified in the DPS (means whose proof of possession has been done) , 


You can use either of the scripts. The script internally used openssl. To see how the script is supposed ot be used please follow https://github.com/Azure/azure-iot-sdk-python-preview/wiki/Creating-X509-chain
This script only generates a 3 level certificate chain.

**Comment by bukarev** [comment]
Thanks for pointing me to this doco on creating X509 chain. The bits that I missed to do were:
1. If Root certificate has been used for Enrollment Group creation, it should be absent in the chain for device registration.
2. In the chain, the Device certificate should go first and be followed by Intermediate, not the other way round.

It works now, thank you!
