### ISSUE TITLE
receive_c2d_message() seems to break when an empty c2d message is sent

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python-preview#144]
I'm running this SDK on Raspbian with Python 3.7.4.

A device has been provisioned using group enrollment and X509 certificate. So I'm running _receive_c2d_message_x509.py_ sample script and sending messages to my device from Azure Portal. It works fine with one exception.

When a message's Body is empty, and only custom properties are set, the Portal reports the message as sent. However, it's not printed out by _receive_c2d_message_x509.py_ script. Any subsequent messages are not printed, either, even if I restart the script. 

When I try to send a d2c message, the following error stack is printed out:

`
ERROR:azure.iot.device.common.pipeline.pipeline_stages_base:Error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTClientStage object at 0xb673ffac>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 94, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 104, in _run_op
    raise e
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 100, in _run_op
    password=self.sas_token, client_certificate=self.trusted_certificate_chain
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 157, in connect
    self._mqtt_client.tls_set_context(context=ssl_context)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 688, in tls_set_context
    raise ValueError('SSL/TLS has already been configured.')
ValueError: SSL/TLS has already been configured.
`

The only way to correct this behaviour is by deleting the device in the Azure Portal and then reprovisioning it.

Seems like a bug on the IoT receiving side?

**Comment by cartertinney** [comment]
We believe this to be an issue with our SDK, and are looking into solutions currently. This is a high priority bug. If you encounter this issue again before a fix is delivered, please try restarting your application rather than deleting and reprovisioning your device.

**Comment by cartertinney** [comment]
This bug has been fixed in #149

**Comment by cartertinney** [comment]
This bug has been fixed in the latest release, 2.0.0-preview.9 (9919643), now available on pip
