### ISSUE TITLE
New Message without explictly set correlation_id AND message_id fails when sent

### ISSUE THREAD

**Issue by bf1967** [Azure/azure-iot-sdk-python-preview#152]
I'm working with the the send_d2c_message.py from the samples folder.

If I don't explicitly set the correlation_id AND the message_id of the message the message fails to send.  Is this behavior by design or a bug?    If one or the other is set it works fine.

Calling send_d2c_message with just a message payload works just fine.  I'm trying to add custom_properties to my message and discovered this behavior.

I can provide logs if needed.

**Comment by olivakar** [comment]
We are looking into it.

**Comment by cartertinney** [comment]
This bug has been fixed in the latest release, 2.0.0-preview.9 (9919643), now available on pip

**Comment by bf1967** [comment]
Your fix did the trick.   Thanks for the quick turnaround @olivakar @cartertinney.
